apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-disk     # 위에서 만든 디스크 이름
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain

