apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  #type: ClusterIP   # 클러스터 내부에서만 접근
  type: LoadBalancer   # 클러스터 내부에서만 접근
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

